### ISSUE TITLE
List all GRIN related public communication channels 

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/2020-grin-bug-bash-challenge#26]
**Description**
List all GRIN related public communication channels where users can get help, get help for GRIN or just discuss the current GRIN market situation.

**Expected result:**
A nice formatted list, as a reference for new users where to find the communication channels.

**Comment by goyle** [comment]
<p align="center">
  <h1 align="center">Grin Community</h1>
  <p align="center">A comprehensive list of Grin-related public communication channels.<p>
  </p>
</p>

## Table of Contents
- [Grin Forum](#grin-forum)
- [Grincoin Keybase](#grincoin-keybase)
- [Discord](#discord)
  - [Grin Community Discord](#grin-community-discord)
  - [GrinHub Discord](#grinhub-discord)
- [Reddit](#reddit)
  - [Grincoin Subreddit](#grincoin-subreddit)
  - [Grin Subreddit](#grin-subreddit)
  - [GrinTrader Subreddit](#grintrader-subreddit)
  - [Mimblewimble Subreddit](#mimblewimble-subreddit)
  - [GrinMarket Subreddit](#grinmarket-subreddit)
- [Telegram](#telegram)
  - [General Telegrams](#general-telegrams)
    - [Grin Community ツ Telegram](#grin-community-ツ-telegram)
    - [Grin Trader Telegram](#grin-trader-telegram)
    - [Grin Hub Telegram](#grin-hub-telegram)
    - [GrinFans Telegram](#grinfans-telegram)
    - [Grin Mining Telegram](#grin-mining-telegram)
    - [MimbleWimble Telegram](#mimblewimble-telegram)
  - [Wallet Support Telegrams](#wallet-support-telegrams)
    - [Grin++ Telegram](#grin++-telegram)
    - [Niffler Wallet Telegram](#niffler-wallet-telegram)
    - [Ironbelly Telegram](#ironbelly-telegram)
  - [International Telegrams](#international-telegrams)
    - [GrinCoin Telegram (Russian)](#grincoin-telegram-russian)
    - [Grin Russia Telegram (Russian)](#grin-russia-telegram-russian)
    - [Grin Mimblewimble Italia Telegram (Italian)](#grin-mimblewimble-italia-telegram-italian)
    - [🇹🇷 GrinKoin 🇹🇷 Telegram (Turkish)](#🇹🇷-grinkoin-🇹🇷-telegram-turkish)
- [ASIC Manufacturer Telegrams](#asic-manufacturer-telegrams)
    - [iPollo & Interhash G1 Miner Telegram](#ipollo-&-interhash-g1-miner-telegram)
- [Gitter](#gitter)
  - [Grin Gitter](#grin-gitter)
  - [GrinGoldMiner Gitter](#gringoldminer-gitter)
- [Matrix.org](#matrixorg)
  - [Mimblewimble Matrix](#mimblewimble-matrix)
- [Status.im](#statusim)
  - [Grin Status](#grin-status)

[grin-forum]: https://img.shields.io/discourse/status?label=forum.grin.mw&logo=discourse&server=https%3A%2F%2Fforum.grin.mw
[grin-forum-topics]: https://img.shields.io/discourse/topics?color=gold&label=%20&server=https%3A%2F%2Fforum.grin.mw
[grin-forum-users]: https://img.shields.io/discourse/users?color=gold&label=%20&server=https%3A%2F%2Fforum.grin.mw
[grin-forum-posts]: https://img.shields.io/discourse/posts?color=gold&label=%20&server=https%3A%2F%2Fforum.grin.mw
[grin-forum-likes]: https://img.shields.io/discourse/likes?color=gold&label=%20&server=https%3A%2F%2Fforum.grin.mw

[grincoin-keybase]: https://img.shields.io/static/v1?logo=keybase&label=grincoin&message=join&logoColor=white&color=blue

[grin-community-discord]: https://img.shields.io/discord/508770582679126017?logo=discord
[grinhub-discord]: https://img.shields.io/discord/500284310331326476?logo=discord

[grincoin-subreddit]: https://img.shields.io/static/v1?logo=reddit&label=%2Fr%2F&message=grincoin&color=red
[grincoin-subreddit-subs]: https://img.shields.io/reddit/subreddit-subscribers/grincoin?label=readers&color=gold
[grin-subreddit]: https://img.shields.io/static/v1?logo=reddit&label=%2Fr%2F&message=GRIN&color=red
[grin-subreddit-subs]: https://img.shields.io/reddit/subreddit-subscribers/GRIN?label=readers&color=gold
[grintrader-subreddit]: https://img.shields.io/static/v1?logo=reddit&label=%2Fr%2F&message=grintrader&color=red
[grintrader-subreddit-subs]: https://img.shields.io/reddit/subreddit-subscribers/grintrader?label=readers&color=gold
[mimblewimble-subreddit]: https://img.shields.io/static/v1?logo=reddit&label=%2Fr%2F&message=Mimblewimble&color=red
[mimblewimble-subreddit-subs]: https://img.shields.io/reddit/subreddit-subscribers/Mimblewimble?label=readers&color=gold
[grinmarket-subreddit]: https://img.shields.io/static/v1?logo=reddit&label=%2Fr%2F&message=GrinMarket&color=red
[grinmarket-subreddit-subs]: https://img.shields.io/reddit/subreddit-subscribers/GrinMarket?label=readers&color=gold

[grin-community-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Grin%20Community%20ツ&message=join&color=blue
[grin-trader-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Grin%20Trader&message=join&color=blue
[grin-hub-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Grin%20Hub&message=join&color=blue
[grinfans-telegram]: https://img.shields.io/static/v1?logo=telegram&label=GrinFans&message=join&color=blue
[grin-mining-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Grin%20Mining&message=join&color=blue
[grin++-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Grin%2B%2B&message=join&color=blue
[mimblewimble-telegram]: https://img.shields.io/static/v1?logo=telegram&label=MimbleWimble&message=join&color=blue
[niffler-wallet-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Niffler%20Wallet&message=join&color=blue
[ironbelly-telegram]: https://img.shields.io/static/v1?logo=telegram&label=Ironbelly&message=join&color=blue
[grincoin-telegram-russian]: https://img.shields.io/static/v1?logo=telegram&label=GrinCoinRussian&message=join&color=blue
[grin-russia-telegram-russian]: https://img.shields.io/static/v1?logo=telegram&label=Grin4Russia&message=join&color=blue
[grin-mimblewimble-italia-telegram-italian]: https://img.shields.io/static/v1?logo=telegram&label=Grin%20Mimblewimble%20Italia&message=join&color=blue
[grinkoin-telegram-turkish]: https://img.shields.io/static/v1?logo=telegram&label=GrinKoin&message=join&color=blue
[ipollo-&-interhash-g1-miner-telegram]: https://img.shields.io/static/v1?logo=telegram&label=iPollo%20%26%20Interhash%20G1%20Miner&message=join&color=blue

[grin-gitter]: https://img.shields.io/gitter/room/mimblewimble/grin?logo=gitter
[gringoldminer-gitter]: https://img.shields.io/gitter/room/mozkomor/GrinGoldMiner?logo=gitter

[mimblewimble-matrix]: https://img.shields.io/static/v1?logo=matrix&label=matrix&message=%23mimblewimble:matrix.org&color=white

[grin-status]: https://img.shields.io/static/v1?label=status.im&message=%23grin&labelColor=4360df&color=white

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394386-177c7080-4b20-11eb-835f-9165b09e0205.jpg" />

## Grin Forum
[![grin-forum]](https://forum.grin.mw/) [![grin-forum-topics]](https://forum.grin.mw/u?order=topic_count) [![grin-forum-users]](https://forum.grin.mw/u) [![grin-forum-posts]](https://forum.grin.mw/latest) [![grin-forum-likes]](https://forum.grin.mw/u?order=likes_given)

### :mega: Description
The official forum to discuss the Grin blockchain and technology. Hosted on the Discourse platform.

### :bookmark_tabs: Categories
_**Announcements and news** from the core developers. Progress updates._ \
_**Mining hardware and software discussion.** ASIC news._ \
_**Tech support**. Wallet support from developers. Exchange and pool issues._ \
_**Development and technical discussion**. Development agendas and meeting notes. Community projects._ \
_**Market** and price discussion. Exchanges. Marketplace. Adoption._ \
_**Governance** agendas and meeting notes. Funding requests. Community management. Code of conduct._ \
_**Research** in cryptocurrency and cryptography. Protocol proposals and ideas. Technical reports._ \
_**Rants and flames.** Constructive complaints. Heated debate._

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| :--------------------------------------- |
| **Admins**      | `tromp`, `lehnberg`, `quentinlesceller`  |
| **Moderators**  | `jaspervdm`, `Yeastplume`                |

### :envelope: Contact
*grinmods at googlegroups.com*

&NewLine;
&NewLine;


<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394386-177c7080-4b20-11eb-835f-9165b09e0205.jpg" />

## Grincoin Keybase
[![grincoin-keybase]](https://keybase.io/team/grincoin)

### :mega: Description
Welcome to Grin's keybase community! 👋 \
Project website with more info: https://grin.mw

### :speech_balloon: Notable Channels
_**#general** - A catch-all lobby where we hold our bi-weekly governance meetings._ \
_**#crypto** - for cryptology research._ \
_**#dev** - for general development and bi-weekly meetings_ \
_**#support** - for help and questions_

_There are also dedicated teams you can join and get some work done:_ \
_**@grincoin.teams.node_dev** - for Node development_ \
_**@grincoin.teams.wallet_dev** - for Wallet development_

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| :--------------------------------------- |
| **Owners** | `antiochp`, `ignotus`, `quentinlesceller`, `yeastplume` |
| **Admins** | `jaspervdm`, `lehnberg`, `tromp`         |

&NewLine;
&NewLine;
<hr>

<h2 align="center">Discord</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394399-1c412480-4b20-11eb-977a-c3ff3f12d5ca.png" />

## Grin Community Discord
[![grin-community-discord]](https://discord.com/invite/wH6uj7z)

### :speech_balloon: Notable Channels
_**#announcements**. Updates on new Grin releases. Community funded projects. Referrals to other Grin channels._ \
_**#general.** Catch-all for everything._ \
_**#mining**. Pool and miner support._\
_**#market-and-price**. Price speculation. Discussion on charts and events._ \
_**#marketing**. Discussion on all aspects of marketing from designing logos, banners, and other creations to actual products._ \
_**#grinmint**. Official mining pool support._ \
_**Language-specific channels.** Chinese, Russian, Turkish, French, Korean, German, Spanish..._ \
_**Voice Channels**. General and gaming._

### :name_badge: Staff
| Roles          | Members                                  |
|:--------------:| :--------------------------------------- |
| **Owner**      | `MCM-Mike#5563`
| **Admins**     | `Sminem#6047`, `yasabi#2385` |
| **Moderators** | `Lokar -=BoA=-#9621`, `rockfist93#3603`, `Seal Clubber#4158` |
| **Retired**    | `russ#0928 (former owner)`, `JustAResearcher#8446 (former admin)`, `.Hardman#0684 (former owner)` |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394379-151a1680-4b20-11eb-9a58-e4739c41b59e.png" />

## GrinHub Discord
[![grinhub-discord]](https://discord.com/invite/PmCb33f)

| :warning: | Obsolete server! |
| --------- | :------------------- |

### :name_badge: Staff
| Roles           | Members                       |
|:---------------:| :---------------------------- |
| **Admins**      | `0x#9454`, `Gus Sulliman#2333`|

&NewLine;
&NewLine;
<hr>

<h2 align="center">Reddit</h2>

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394383-177c7080-4b20-11eb-8553-7f0763938f1f.png" />

## Grincoin Subreddit
[![grincoin-subreddit]](https://reddit.com/r/grincoin/) [![grincoin-subreddit-subs]](https://reddit.com/r/grincoin/)

### :mega: Description
Grin is a simple, privacy-focused, scalable MimbleWimble protocol implementation. It aims to provide a fungible means of electronic transactions for all.

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| ---------------------------------------- |
| **Moderators** | `yUnoPOLO`, `berryfarmer`, `0xb100d`, `Paouky` |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394388-18ad9d80-4b20-11eb-8191-fb432c1af8a8.png" />

## Grin Subreddit
[![grin-subreddit]](https://reddit.com/r/GRIN/) [![grin-subreddit-subs]](https://reddit.com/r/GRIN/)

### :mega: Description
A subreddit for discussing the Grin cryptocurrency based on the Mimblewimble whitepaper.

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| ---------------------------------------- |
| **Moderators** | `yUnoPOLO`, `berryfarmer`, `0xb100d` |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394377-13e8e980-4b20-11eb-8796-4ba91fc4b975.png" />

## GrinTrader Subreddit
[![grintrader-subreddit]](https://reddit.com/r/grintrader/) [![grintrader-subreddit-subs]](https://reddit.com/r/grintrader/)

### :mega: Description
Welcome to /r/GrinTrader, a 100% community driven sub. Here you can discuss Grin/Mimblewimble news, memes, investing, trading, miscellaneous market-related subjects and other relevant technology.

### :name_badge: Staff
| Roles          | Members                                  |
|:--------------:| ---------------------------------------- |
| **Moderators** | `krakrakra`, `0xb100d`                   |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394375-13505300-4b20-11eb-845e-a291ac31cc7e.png" />

## Mimblewimble Subreddit
[![mimblewimble-subreddit]](
https://reddit.com/r/Mimblewimble/) [![mimblewimble-subreddit-subs]](
https://reddit.com/r/Mimblewimble/)

### :mega: Description
Mimblewimble is the name of a [whitepaper](https://download.wpsoftware.net/bitcoin/wizardry/mimblewimble.txt) published in 2016 by pseudonymous contributor. The paper proposes a radical restructuring of the Bitcoin protocol in order to massively improve privacy and scalability of the digital currency. It is named after the Tongue-Tying Curse in Harry Potter because it aims to prevent users from saying too much about their transactions.

### :name_badge: Staff
| Roles          | Members                                  |
|:--------------:| ---------------------------------------- |
| **Moderators** | `BashCo`, `0xb100d`                      |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394378-14818000-4b20-11eb-8675-c642b9a8b3c1.png" />

## GrinMarket Subreddit
[![grinmarket-subreddit]](
https://reddit.com/r/GrinMarket/) [![grinmarket-subreddit-subs]](
https://reddit.com/r/GrinMarket/)

### :mega: Description
Welcome to /r/GrinMarket, a 100% community driven sub. Here you can discuss Grin/Mimblewimble investing, trading, miscellaneous market-related subjects around Grin.

### :name_badge: Staff
| Roles          | Members                                  |
|:--------------:| ---------------------------------------- |
| **Moderators** | `krakrakra`, `0xb100d`                   |

&NewLine;
&NewLine;
<hr>

<h2 align="center">Telegram</h2>

&NewLine;
&NewLine;

<h2 align="center">General Telegrams</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394397-1ba88e00-4b20-11eb-93b3-465f72965659.jpg" />

## Grin Community ツ Telegram
[![grin-community-telegram]](https://t.me/grinprivacy)

### :mega: Description
Hi All, welcome to the Grin Community ( formally known as Grin Hub).   

This is not the "official" Grin group, there is no official Grin group or official anything, because, Grin strives to be a decentralized project with no central point of failure. 

Grin is different. It's a fair launch/ community backed/ grass roots project and is the OG implementation of the Mimblewimble protocol, built primarily in Rust. It's focus is to build a private and scalable P2P currency- Grin aims to become the digital cash to Bitcoin's digital gold. 

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| :--------------------------------------- |
| **Admins** | `M̆ͦâ̚c̍ͣ ツ (@future3000)`, `David Burkett (@DavidBurkett)` |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394387-18150700-4b20-11eb-96aa-192959a10191.jpg" />

## Grin Trader Telegram
[![grin-trader-telegram]](https://t.me/grintrader)

### :mega: Description
Welcome to grintrader. A place where you can talk about all traded related things regarding Grin.

### :name_badge: Staff
| Roles           | Members                                  |
|:---------------:| :--------------------------------------- |
| **Admins** | `M̆ͦâ̚c̍ͣ ツ (@future3000)` |

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394394-1a776100-4b20-11eb-99fc-5f6292e1ef47.jpg" />

## Grin Hub Telegram
[![grin-hub-telegram]](https://t.me/GrinCoin)

| :warning: | Migrated to [Grin Community ツ Telegram](#grin-community-ツ-telegram) ([More info on Twitter.](https://twitter.com/grin_privacy/status/1325616441719054336)) |
|---------------|:------------------------|

### :mega: Description
Grin ( ツ) is a lightweight MimbleWimble protocol implementation.

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394381-164b4380-4b20-11eb-85fc-25df2c00b0d5.jpg" />

## GrinFans Telegram
[![grinfans-telegram]](https://t.me/grinfans)

### :mega: Description
Welcome to the wizarding world of Grin! GrinFans is an community discussion group created to help spread knowledge about the Grin project.

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394391-19463400-4b20-11eb-8dd5-336ef3fb307b.jpg" />

## Grin Mining Telegram
[![grin-mining-telegram]](https://t.me/GrinMining)

### :mega: Description
Grin mining discussion and shit posting, no spam or you will be ridiculed into oblivion. Check out bitcoinMINING chat for latest CSW memes.

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/104450204-a1542100-5597-11eb-9bdc-872380d94571.jpg" />

## MimbleWimble Telegram
[![mimblewimble-telegram]](https://t.me/mimble_wimble/)

&NewLine;
&NewLine;
<hr>

<h2 align="center">Wallet Support Telegrams</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394402-1cd9bb00-4b20-11eb-9cd8-5a796c5c4063.jpg" />

## Grin++ Telegram
[![grin++-telegram]](https://t.me/GrinPP)

### :mega: Description
Grin++ wallet: https://grinplusplus.github.io/

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394374-11868f80-4b20-11eb-9d26-dedb006b936b.jpg" />

## Niffler Wallet Telegram
[![niffler-wallet-telegram]](https://t.me/nifflerwallet)

### :mega: Description
Niffler wallet: https://github.com/grinfans/Niffler

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394376-13505300-4b20-11eb-9a17-c98f3059a1d4.jpg" />

## Ironbelly Telegram
[![ironbelly-telegram]](https://t.me/ironbelly)

### :mega: Description
Ironbelly mobile wallet: https://ironbelly.app/

&NewLine;
&NewLine;
<hr>

<h2 align="center">International Telegrams</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394382-16e3da00-4b20-11eb-80fa-6d44d1ba703d.jpg" />

## GrinCoin Telegram (Russian)
[![grincoin-telegram-russian]](https://t.me/GrinCoinRussian)

### :mega: Description
Неофициальный русскоговорящий чат Grin http://grin.mw/ \
Рекомендованный пул для добычи https://woolypooly.com/#/coin/grin

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/113048905-8f474f00-9192-11eb-995e-860a12f55896.jpg" />

## Grin Russia Telegram (Russian)
[![grin-russia-telegram-russian]](https://t.me/Grin4Russia)

### :mega: Description
Новости. Обсуждение Grin и MW.

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394392-19deca80-4b20-11eb-8e15-ad2a9b107a1d.jpg" />

## Grin Mimblewimble Italia Telegram (Italian)
[![grin-mimblewimble-italia-telegram-italian]](https://t.me/grinitalia)

### :mega: Description
Grin mimblewimble Italia, gruppo dedicato alle discussioni su questa tecnologia, mining, coin.

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103407817-efa8ff00-4b57-11eb-9ae3-486bdbfdb8b8.jpg" />

## 🇹🇷 GrinKoin 🇹🇷 Telegram (Turkish)
[![grinkoin-telegram-turkish]](https://t.me/Grin_TR)

### :mega: Description
GRİN Tartışma,fiyat takibi,bilgi amaçlı grup.**Yatırım tavsiyesi verilmez. \
Kripto paralar hala deneysel aşamadadır.Yüksek risk içerir. \
Bir kişiye özel tavsiye ve yönlendirici nitelikli yorumlar yatırım danışmanlığı kapsamına girdiği için yasaktır.

&NewLine;
&NewLine;
<hr>

<h2 align="center">ASIC Manufacturer Telegrams</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/108088954-f4c2fe80-7070-11eb-9fe3-0ed16286e435.jpg" />

## iPollo & Interhash G1 Miner Telegram
[![ipollo-&-interhash-g1-miner-telegram]](https://t.me/iPolloGlobal)

### :mega: Description
https://www.ipollo.com/ipollo_en/interhashMikecrm.html

**1、 Product**
 
G1-Mini is ASIC Miner, is the mini-sized domestic version of G1.

**2、Price**
 
Initial offering price of G1-Mini: has been sold out.
 
All digital currency involved in this sale will be uniformly charged and processed by iPollo's strategic partner Interhash.
 
To improve the liquidity in Grin network, you need to pay with Grin and you can get a discount of 5% (The exchange rate is confirmed with our sales staff in real time).
 
This price is only for the device, which means other expenses like express fee and insurance expenses are not included.
 
**3、Delivery**
 
Has been sold out.
 
**4、Order**

You can contact our sales in three ways:
1. WeChat: interhash
2. Telegram: https://t.me/iPolloGlobal. You can ask questions directly in the telegram group.
3. Email: interhash@ipollo.com
 
If you can't reach us through the first two ways, you can contact us by email. Further, you can send messages to our sales' personal email address.

For more questions, please contact our staff through the above three ways.

&NewLine;
&NewLine;
<hr>

<h2 align="center">Gitter</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394395-1b0ff780-4b20-11eb-99e3-b83f2c2664a0.png" />

## Grin Gitter
[![grin-gitter]](https://gitter.im/grin_community)

| :warning: | Discontinued: Main chat moved to [Keybase](#grincoin-keybase)! |
|---------------|:------------------------|

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/103394380-15b2ad00-4b20-11eb-965a-efab00ea5dfe.png" />

## GrinGoldMiner Gitter
[![gringoldminer-gitter]](https://gitter.im/GrinGoldMiner)

| :warning: | Discontinued: [GrinGoldMiner](https://github.com/mozkomor/GrinGoldMiner) does NOT work on current Grin chain! |
|---------------|:------------------------|

&NewLine;
&NewLine;
<hr>

<h2 align="center">Matrix.org</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/104089485-67b5aa00-5267-11eb-8763-80bca90c2333.jpg" />

## Mimblewimble Matrix
[![mimblewimble-matrix]](https://matrix.to/#/!lAuZpDdhLNEIsbiEdV:matrix.org)

| :warning: | Inactive server! |
|---------------|:------------------------|

&NewLine;
&NewLine;
<hr>

<h2 align="center">Status.im</h2>

&NewLine;
&NewLine;

<img align="left" height="80px" width="80px" alt="Server Icon" src="https://user-images.githubusercontent.com/62769624/104089283-8adf5a00-5265-11eb-8142-bb4d7f24112e.png" />

## Grin Status
[![grin-status]](https://join.status.im/grin)

**Comment by goyle** [comment]
If there is any more channels, let me know and I can add it to the list.

**Comment by marekyggdrasil** [comment]
Awesome work! Thanks @goyle !
